/* This file is autogenerated, do not edit*/
#include "cw2_automoc.dir/moc_mySlider_NTSTY3RYSYHEH6.cpp"
#include "cw2_automoc.dir/moc_one_LTVKPH6CEOLAHL.cpp"
#include "cw2_automoc.dir/moc_pages_2ZHZLVRNVEP723.cpp"
#include "cw2_automoc.dir/moc_the_button_XDARI7HC7VIRXO.cpp"
#include "cw2_automoc.dir/moc_the_player_2BR5LKUESNRDOP.cpp"
#include "cw2_automoc.dir/moc_three_HEVFM3PPQNBW2I.cpp"
#include "cw2_automoc.dir/moc_two_ZSDFPHM4QDYRGK.cpp"
