# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/cserv1_b/apps/install/clion/2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/cserv1_b/apps/install/clion/2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/csunix/sc17h2z/CLionProjects/cw2 (2rd)"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/csunix/sc17h2z/CLionProjects/cw2 (2rd)"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/cserv1_b/apps/install/clion/2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/cserv1_b/apps/install/clion/2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/csunix/sc17h2z/CLionProjects/cw2 (2rd)/CMakeFiles" "/home/csunix/sc17h2z/CLionProjects/cw2 (2rd)/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/csunix/sc17h2z/CLionProjects/cw2 (2rd)/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cw2

# Build rule for target.
cw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2
.PHONY : cw2

# fast build rule for target.
cw2/fast:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/build
.PHONY : cw2/fast

#=============================================================================
# Target rules for targets named cw2_automoc

# Build rule for target.
cw2_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2_automoc
.PHONY : cw2_automoc

# fast build rule for target.
cw2_automoc/fast:
	$(MAKE) -f CMakeFiles/cw2_automoc.dir/build.make CMakeFiles/cw2_automoc.dir/build
.PHONY : cw2_automoc/fast

cw2_automoc.o: cw2_automoc.cpp.o

.PHONY : cw2_automoc.o

# target to build an object file
cw2_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_automoc.cpp.o
.PHONY : cw2_automoc.cpp.o

cw2_automoc.i: cw2_automoc.cpp.i

.PHONY : cw2_automoc.i

# target to preprocess a source file
cw2_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_automoc.cpp.i
.PHONY : cw2_automoc.cpp.i

cw2_automoc.s: cw2_automoc.cpp.s

.PHONY : cw2_automoc.s

# target to generate assembly for a file
cw2_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_automoc.cpp.s
.PHONY : cw2_automoc.cpp.s

mySlider.o: mySlider.cpp.o

.PHONY : mySlider.o

# target to build an object file
mySlider.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/mySlider.cpp.o
.PHONY : mySlider.cpp.o

mySlider.i: mySlider.cpp.i

.PHONY : mySlider.i

# target to preprocess a source file
mySlider.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/mySlider.cpp.i
.PHONY : mySlider.cpp.i

mySlider.s: mySlider.cpp.s

.PHONY : mySlider.s

# target to generate assembly for a file
mySlider.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/mySlider.cpp.s
.PHONY : mySlider.cpp.s

one.o: one.cpp.o

.PHONY : one.o

# target to build an object file
one.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/one.cpp.o
.PHONY : one.cpp.o

one.i: one.cpp.i

.PHONY : one.i

# target to preprocess a source file
one.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/one.cpp.i
.PHONY : one.cpp.i

one.s: one.cpp.s

.PHONY : one.s

# target to generate assembly for a file
one.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/one.cpp.s
.PHONY : one.cpp.s

pages.o: pages.cpp.o

.PHONY : pages.o

# target to build an object file
pages.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/pages.cpp.o
.PHONY : pages.cpp.o

pages.i: pages.cpp.i

.PHONY : pages.i

# target to preprocess a source file
pages.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/pages.cpp.i
.PHONY : pages.cpp.i

pages.s: pages.cpp.s

.PHONY : pages.s

# target to generate assembly for a file
pages.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/pages.cpp.s
.PHONY : pages.cpp.s

sysWindow.o: sysWindow.cpp.o

.PHONY : sysWindow.o

# target to build an object file
sysWindow.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/sysWindow.cpp.o
.PHONY : sysWindow.cpp.o

sysWindow.i: sysWindow.cpp.i

.PHONY : sysWindow.i

# target to preprocess a source file
sysWindow.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/sysWindow.cpp.i
.PHONY : sysWindow.cpp.i

sysWindow.s: sysWindow.cpp.s

.PHONY : sysWindow.s

# target to generate assembly for a file
sysWindow.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/sysWindow.cpp.s
.PHONY : sysWindow.cpp.s

the_button.o: the_button.cpp.o

.PHONY : the_button.o

# target to build an object file
the_button.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.o
.PHONY : the_button.cpp.o

the_button.i: the_button.cpp.i

.PHONY : the_button.i

# target to preprocess a source file
the_button.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.i
.PHONY : the_button.cpp.i

the_button.s: the_button.cpp.s

.PHONY : the_button.s

# target to generate assembly for a file
the_button.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.s
.PHONY : the_button.cpp.s

the_player.o: the_player.cpp.o

.PHONY : the_player.o

# target to build an object file
the_player.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.o
.PHONY : the_player.cpp.o

the_player.i: the_player.cpp.i

.PHONY : the_player.i

# target to preprocess a source file
the_player.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.i
.PHONY : the_player.cpp.i

the_player.s: the_player.cpp.s

.PHONY : the_player.s

# target to generate assembly for a file
the_player.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.s
.PHONY : the_player.cpp.s

three.o: three.cpp.o

.PHONY : three.o

# target to build an object file
three.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/three.cpp.o
.PHONY : three.cpp.o

three.i: three.cpp.i

.PHONY : three.i

# target to preprocess a source file
three.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/three.cpp.i
.PHONY : three.cpp.i

three.s: three.cpp.s

.PHONY : three.s

# target to generate assembly for a file
three.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/three.cpp.s
.PHONY : three.cpp.s

tomeo.o: tomeo.cpp.o

.PHONY : tomeo.o

# target to build an object file
tomeo.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.o
.PHONY : tomeo.cpp.o

tomeo.i: tomeo.cpp.i

.PHONY : tomeo.i

# target to preprocess a source file
tomeo.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.i
.PHONY : tomeo.cpp.i

tomeo.s: tomeo.cpp.s

.PHONY : tomeo.s

# target to generate assembly for a file
tomeo.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.s
.PHONY : tomeo.cpp.s

two.o: two.cpp.o

.PHONY : two.o

# target to build an object file
two.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/two.cpp.o
.PHONY : two.cpp.o

two.i: two.cpp.i

.PHONY : two.i

# target to preprocess a source file
two.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/two.cpp.i
.PHONY : two.cpp.i

two.s: two.cpp.s

.PHONY : two.s

# target to generate assembly for a file
two.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/two.cpp.s
.PHONY : two.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cw2"
	@echo "... cw2_automoc"
	@echo "... cw2_automoc.o"
	@echo "... cw2_automoc.i"
	@echo "... cw2_automoc.s"
	@echo "... mySlider.o"
	@echo "... mySlider.i"
	@echo "... mySlider.s"
	@echo "... one.o"
	@echo "... one.i"
	@echo "... one.s"
	@echo "... pages.o"
	@echo "... pages.i"
	@echo "... pages.s"
	@echo "... sysWindow.o"
	@echo "... sysWindow.i"
	@echo "... sysWindow.s"
	@echo "... the_button.o"
	@echo "... the_button.i"
	@echo "... the_button.s"
	@echo "... the_player.o"
	@echo "... the_player.i"
	@echo "... the_player.s"
	@echo "... three.o"
	@echo "... three.i"
	@echo "... three.s"
	@echo "... tomeo.o"
	@echo "... tomeo.i"
	@echo "... tomeo.s"
	@echo "... two.o"
	@echo "... two.i"
	@echo "... two.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

